[functions.create-user]
verify_jwt = false

[functions.webhook]
verify_jwt = false

[functions.verify-worldid]
verify_jwt = false

[functions.forgot-password]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.telegram-login]
verify_jwt = false

[functions.connect-telegram-notifications]
verify_jwt = true

[functions.loan-funded-notification]
verify_jwt = true

[functions.loan-due-notifications]
verify_jwt = false

[functions.loan-request-telegram-notification]
verify_jwt = false

[functions.loan-overdue-notifications]
verify_jwt = false

[functions.loan-weekly-digest]
verify_jwt = false

[functions.loan-request-expired-notifications]
verify_jwt = false
