-- Make the wallet face gate's own signals actually reach a human, and watch for stuck mints.
--
-- Two gaps found reviewing 20260811000000:
--
--  1. The webhook writes wallet face collisions straight into fraud_signal_alerts, but
--     fraud-signal-scan only emails what scan_wallet_fraud_signals RETURNS. Rows inserted by
--     anyone else are never read, so the "critical: a borrower and a lender are the same
--     person" signal was recorded and then silently ignored. A fraud control nobody sees is
--     not a control.
--
--  2. embedded_wallet_grants is claimed BEFORE the Shield mint, so a failed mint leaves a
--     grant with a null wallet_address. That ordering is deliberate — it lets the user retry
--     without paying for a second face scan — but it means a Shield outage strands people
--     silently, and nothing watched for it.

-- ---------------------------------------------------------------------------
-- 1. Let externally-inserted alerts be picked up exactly once.
--
-- The existing signals are generated BY the scan and deduped with a "not exists" check
-- against their own subject_key. Rows written by the webhook can't use that pattern (they
-- are already in the table by the time the scan runs), so they need their own delivery mark.
-- Backfilled as already-reported: existing history is not new news.
-- ---------------------------------------------------------------------------
alter table public.fraud_signal_alerts add column if not exists reported_at timestamptz;

update public.fraud_signal_alerts
   set reported_at = coalesce(reported_at, created_at)
 where reported_at is null;

create index if not exists fraud_signal_alerts_unreported_idx
   on public.fraud_signal_alerts (signal_type)
   where reported_at is null;

-- ---------------------------------------------------------------------------
-- 2. Fold both into the existing daily scan, so this rides the alert path that already
--    works (Telegram + email via fraud-signal-scan) instead of inventing a second one.
-- ---------------------------------------------------------------------------
create or replace function public.scan_wallet_face_signals(stuck_grant_minutes integer default 60)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
   new_signals jsonb := '[]'::jsonb;
   rec record;
   stuck_count integer;
begin
   -- A. Wallet face signals the webhook recorded but nobody has been told about yet.
   for rec in
      select a.id, a.signal_type, a.subject_key, a.details
      from public.fraud_signal_alerts a
      where a.reported_at is null
        and a.signal_type in ('embedded_wallet_face_collision', 'wallet_face_unverified_self_match')
      order by a.created_at asc
      limit 50
   loop
      new_signals := new_signals || jsonb_build_object(
         'type', rec.signal_type,
         'severity', coalesce(rec.details ->> 'severity', 'warning'),
         'user_id', rec.details ->> 'user_id',
         'user_role', rec.details ->> 'user_role',
         'borrower_and_lender', coalesce((rec.details ->> 'borrower_and_lender')::boolean, false),
         'details', rec.details);

      update public.fraud_signal_alerts set reported_at = now() where id = rec.id;
   end loop;

   -- B. Grants claimed but never completed. A handful is normal (someone closed the tab);
   -- a spike means Shield is failing and users are silently losing wallets they scanned for.
   select count(*) into stuck_count
   from public.embedded_wallet_grants g
   where g.wallet_address is null
     and g.granted_at < now() - make_interval(mins => greatest(coalesce(stuck_grant_minutes, 60), 1));

   if stuck_count > 0 then
      -- Re-alert only when the number changes, so a steady trickle doesn't nag daily.
      if not exists (
         select 1 from public.fraud_signal_alerts a
         where a.signal_type = 'embedded_wallet_grant_stuck'
           and a.subject_key = stuck_count::text
      ) then
         insert into public.fraud_signal_alerts (signal_type, subject_key, details, reported_at)
         values ('embedded_wallet_grant_stuck', stuck_count::text,
                 jsonb_build_object('stuck_count', stuck_count, 'severity', 'warning'), now());

         new_signals := new_signals || jsonb_build_object(
            'type', 'embedded_wallet_grant_stuck',
            'severity', 'warning',
            'stuck_count', stuck_count,
            'details', jsonb_build_object(
               'note', 'Instant wallet grants claimed but never completed — check Openfort Shield health.'));
      end if;
   end if;

   return jsonb_build_object(
      'generated_at', now(),
      'new_signal_count', jsonb_array_length(new_signals),
      'signals', new_signals);
end;
$$;

revoke all on function public.scan_wallet_face_signals(integer) from public;
revoke all on function public.scan_wallet_face_signals(integer) from anon;
revoke all on function public.scan_wallet_face_signals(integer) from authenticated;
grant execute on function public.scan_wallet_face_signals(integer) to service_role, postgres;
